# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ItunesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ItunesApp

	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxDataSources'
  	pod 'SnapKit'
	pod 'SDWebImage'
	pod 'RealmSwift'

end
